### PR TITLE
Implemented Add To Front

### PR DESCRIPTION
**Pull request by Sparhawk96**
Changed the generic types of the head and tail. Also added a Constructor to the Node Struct.

Finished Implementing the AddToFront Method.

### CODE REVIEW

**Comment by Sparhawk96** [comment]
The last commit should have been in a separate branch. Since we are trying to get this done I'm going to leave it.

**Review by SMBSU — APPROVED** [review]
Overall looks good. I assume the added remove method is the error you were talking about.

**Comment by Sparhawk96** [comment]
> Overall looks good. I assume the added remove method is the error you were talking about.

Yep.

**Review by EmmaLytle — APPROVED** [review]
Looks good.

**Review by droycho — APPROVED** [review]

**Pull request merged**
